apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "kagent.fullname" . }}
  namespace: {{ .Values.virtualservice.namespace }}
  labels:
    app: {{ include "kagent.fullname" . }}
spec:
  gateways:
  {{- range $hosts := .Values.virtualservice.gateways }}
  - {{ $hosts }}
  {{- end }}
  hosts:
    - {{ .Values.virtualservice.hostname | quote }}
  http:
  - route:
      - destination:
          host: {{ include "kagent.fullname" . }}
          port:
            number: {{ .Values.virtualservice.port }}

